import {StyleSheet,Dimensions} from 'react-native';
var {height, width} = Dimensions.get('window');
let styles = {
  container: {
    flex: 1,
    backgroundColor:'#fff',
  },
  head_img:{
    width: width,
    height: width/(16/9)
  },
  head:{
    height:56,
    paddingTop:14,
    alignItems:'center',
    flexDirection:'row',
    backgroundColor:'#248BFC',
  },
  headwidth:{
    width:width/3,
    alignItems:'center'
  },
  headTopLeft:{
    tintColor:'#fff',
    width:20,
    height:20,
    marginRight:width/3-30
  },
  headTopRight:{
    width:20,
    height:20,
    marginLeft:width/3-45
  },
  weather:{
    position:'absolute',
    right:20,
    top:30,
    zIndex:1,
    alignItems:'flex-end',
    backgroundColor:'transparent'
  },
  weather_city:{
    color:'#fff',
    fontSize:18,
    padding:3
  },
  weather_clound:{
    color:'#fff',
    fontSize:16,
    padding:3
  },
  weather_tem:{
    color:'#fff',
    fontSize:23
  },
  headtitle:{
    color:'#fff',
    fontSize:18
  },
  home_top_view:{
    position:'absolute',
    bottom:10,
    left:20,
    backgroundColor:'rgba(255,255,255,0)'
  },
  home_top_txt:{
    color:'#fff'
  },
  home_top_num:{
    flexDirection:'row'
  },
  home_top_txt_size:{
    fontSize:36,
  },
  home_title:{
    width:width*0.92,
    marginLeft:width*0.04,
    marginTop:width*0.04,
    height:60,
    backgroundColor:'#fff'
  },
  home_note_style:{
    flexDirection:'row'
  },
  home_color_red:{
    width:5,
    height:60,
    borderRadius:5,
    backgroundColor:'red',
  },
  home_color_blue:{
    width:5,
    height:60,
    borderRadius:5,
    backgroundColor:'#509aff',
  },
  home_color_yellow:{
    width:5,
    height:60,
    borderRadius:5,
    backgroundColor:'#ffb23b',
  },
  home_color_green:{
    width:5,
    height:60,
    borderRadius:5,
    backgroundColor:'#4CAF50',
  },
  home_color_pink:{
    width:5,
    height:60,
    borderRadius:5,
    backgroundColor:'#E45CB2',
  },
  home_note:{
    marginLeft:15,
    marginTop:15
  },
  home_star:{
    position:'absolute',
    right:15,
    top:20
  },
  home_note_title:{
    fontSize:15,
    width:width*0.7
  },
  home_note_time:{
    fontSize:11,
    marginTop:5,
    color:'#888'
  },
  home_note_star:{
    width:20,
    height:20
  },
  add_txt:{
    paddingTop:10,
    paddingLeft:20,
    paddingRight:20,
    paddingBottom:10,
    backgroundColor:'#fff',
  },
  add_input:{
    height:120,
  },
  pic_row:{
    marginTop:15,
    flexDirection:'row'
  },
  pic_del_show:{
    position:'absolute',
    top:-8,
    right:-5,
    zIndex:1
  },
  pic_del:{
    width:20,
    height:20,
  },
  show_pic:{
    width:60,
    height:60,
  },
  add_new_pic:{
    marginRight:10
  },
  add_pic_view:{
    backgroundColor:'#ddd',
    width:60,
    height:60,
    alignItems:'center',
    justifyContent:'center',
  },
  add_pic:{
    width:20,
    height:20
  },
  add_pic_txt:{
    fontSize:8
  },
  sel_color:{
    paddingLeft:20,
    paddingRight:20,
    marginTop:15,
    height:50,
    backgroundColor:'#fff',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between'
  },
  color_row:{
    flexDirection:'row',
  },
  note_color:{
    width:15,
    height:15,
    borderWidth:2,
    borderRadius:15,
    marginLeft:20
  },
  note_color_txt:{
    fontSize:18
  },
  red:{
    borderColor:'red',
  },
  blue:{
    borderColor:'#509aff'
  },
  yellow:{
    borderColor:'#ffb23b'
  },
  green:{
    borderColor:'#4CAF50'
  },
  pink:{
    borderColor:'#E45CB2'
  },
  select_red:{
    backgroundColor:'red'
  },
  select_blue:{
    backgroundColor:'#509aff'
  },
  select_yellow:{
    backgroundColor:'#ffb23b'
  },
  select_green:{
    backgroundColor:'#4CAF50'
  },
  select_pink:{
    backgroundColor:'#E45CB2'
  },
  note_see:{
    flexDirection:'row'
  },
  note_see_txt:{
    fontSize:12,
    marginTop:4,
    marginLeft:5
  },
  note_arrow:{
    width:15,
    height:15,
    marginLeft:5
  },
  note_map:{
    color:'#509aff',
  },
  square_view:{
    marginTop:10,
    marginLeft:10,
    marginRight:10,
    padding:12,
    backgroundColor:'#fff'
  },
  square_note_title:{
    fontSize:18,
    width:width*0.8
  },
  square_note_view:{
    flexDirection:'row',
    alignItems:'center',
    marginTop:10
  },
  square_view_avator:{
    width:40,
    height:40,
    borderRadius:20,
    borderWidth:1,
    borderColor:'#ddd'
  },
  square_author:{
    marginLeft:10,
  },
  square_author_name:{
    fontSize:16,
    color:'#545454'
  },
  square_author_time:{
    fontSize:12,
    color:'#87989c'
  },
  square_note_pic:{
    marginBottom:10,
    width:width-44,
    resizeMode:'cover',
    height:(width-44)/(16/9),
    borderRadius:5
  },
  detail_body:{
    backgroundColor:'#fff'
  },
  note_d_view:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    height:30,
    width:width,
    backgroundColor:'#248BFC',
  },
  note_d_icon_view:{
    flexDirection:'row'
  },
  note_d_name:{
    color:'#fff',
    marginLeft:10
  },
  note_d_icon:{
    height:20,
    width:20,
    marginRight:10,
    marginLeft:5
  },
  note_d_body:{
    padding:10,
  },
  note_d_txt:{
    fontSize:16,
    letterSpacing:3,
    lineHeight:20
  },
  note_d_pic:{
    width:width-20,
    height:(width-20)/(16/9),
    marginTop:15,
    resizeMode:'contain',
    borderRadius:5
  },
  serect_show:{
    height:40,
    backgroundColor:'#3D9AFA',
    alignItems:'center',
    justifyContent:'center',
    marginBottom:15,
    marginLeft:30,
    marginRight:30,
    borderRadius:8
  },
  serect_txt:{
    fontSize:16,
    fontWeight:'800',
    color:'#fff'
  },
  secret_input:{
    height:160,
    margin:15,
    backgroundColor:'#fff'
  },
  secret_switch:{
    flexDirection:'row',
    margin:15,
    justifyContent:'space-between'
  },
  secret_txt:{
    marginTop:8,
    fontSize:16,
    color:'#666'
  },
  secret_num:{
    flexDirection:'row',
    justifyContent:'flex-end',
    marginRight:25,
    marginTop:-35,
    backgroundColor:'rgba(0,0,0,0)'
  },
  secret_foot:{
    fontSize:12,
    color:'#898989'
  },
  map_list:{
    marginTop:10,
    marginBottom:10,
    paddingLeft:10,
    paddingRight:10
  },
  map_name:{
    fontSize:16
  },
  map_default:{
    paddingLeft:10,
    marginTop:20,
    paddingBottom:20,
    borderBottomWidth:1,
    borderBottomColor:'#bbb'
  },
  map_default_name:{
    fontSize:16,
    color:'#666'
  },
  map_detail:{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:10
  },
  map_info:{
    fontSize:12,
    color:'#666',
  },
  map_name:{
    width:width*0.6
  },
  selected_img:{
    width:20,
    height:20,
    marginRight:20
  },
  centering:{
    height:height,
    width:width,
    position:'absolute',
    justifyContent:'center',
    alignItems:'center',
  },
  login_center:{
    width:width*0.8,
    height:height*0.5,
  },
  center:{
    height:height,
    width:width,
    position:'absolute',
    justifyContent:'center',
    //alignItems:'center',
  },
  login_title:{
    alignItems:'center',
    marginTop:-height*0.3,
    borderRadius:20,
    marginBottom:40,
  },
  login_txt:{
    fontSize:38,
    color:'#fff',
    backgroundColor:'transparent'
  },
  login_inputView:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    height:60,
    width:width*0.8,
    marginLeft:width*0.1,
    borderColor:'#fff',
    borderBottomWidth:2,
  },
  login_input:{
    width:width*0.6,
    marginBottom:-20,
    fontSize:16,
    color:'#fff'
  },
  login_forget:{
    position:'absolute',
    backgroundColor:'transparent',
    right:0,
    bottom:10
  },
  inputImg:{
    height:30,
    width:30,
    marginBottom:-15,
    marginRight:15
  },
  login_btn:{
    alignItems:'center',
    justifyContent:'center',
    marginLeft:width*0.2,
    width:width*0.6,
    marginTop:35,
    height:40,
    borderRadius:20,
    backgroundColor:'#573A58'
  },
  sms_login:{
    alignItems:'center',
    justifyContent:'center',
    marginTop:35,
    borderRadius:20,
  },
  login_reg:{
    alignItems:'center',
    justifyContent:'center',
    height:40
  },
  login_reg_txt:{
    fontSize:16,
    color:'#864C64',
    fontWeight:'bold'
  },
  bg:{
    width:width,
    height:height-40,
  },
  notice_body:{
    margin:10,
    backgroundColor:'#fff',
    borderRadius:8,
    borderWidth:1,
    borderColor:'#ddd',
  },
  notice_head:{
    flexDirection:'row',
    padding:5,
  },
  notice_user:{
    marginRight:10
  },
  notice_time:{
    fontSize:11,
    color:'#444',
    marginTop:5
  },
  notice_uesr_info:{
    marginLeft:10,
    marginTop:5
  },
  notice_detail:{
    padding:5,
    marginTop:1,
    marginLeft:5,
    marginRight:5,
  },
  /*
    *个人中心
    */
  member_avator_view:{
    alignItems:'center',
    marginTop:15,
    marginBottom:20
  },

  member_avator:{
    height:120,
    width:120,
    borderRadius:60,
    resizeMode:'cover',
    borderWidth:2,
    borderColor:'#fff'
  },
  member_body:{
    paddingTop:5,
    paddingLeft:10,
    paddingRight:10,
  },
  member_list:{
    flexDirection:'row',
    borderBottomWidth:1,
    borderBottomColor:'#ccc',
    paddingBottom:10,
    paddingTop:6
  },
  member_list_info:{
    marginTop:6,
    marginLeft:15
  },
  member_list_info_bg:{
    width:20,
    height:20,
    borderRadius:20,
    backgroundColor:'#f44336',
    position:'absolute',
    right:30,
    top:10
  },
  member_list_info_num:{
    marginTop:1,
    marginLeft:5,
    color:'#fff'
  },
  member_list_icon:{
    width:25,
    height:25
  },
  member_list_arrow:{
    width:15,
    height:15,
    position:'absolute',
    right:0,
    top:11
  },
  member_info_body:{
    paddingTop:10,
    paddingLeft:20,
    paddingRight:20
  },
  member_info_avator:{
    width:50,
    height:50,
    borderRadius:25,
    position:'absolute',
    right:35
  },
  member_info_arrow:{
    width:20,
    height:20,
    position:'absolute',
    right:10
  },
  member_info_first:{
    flexDirection:'row',
    padding:5,
    alignItems:'center',
    height:60,
    borderBottomWidth:1,
    borderBottomColor:'#ddd'
  },
  member_info_title:{
    flexDirection:'row',
    padding:5,
    alignItems:'center',
    height:40,
    borderBottomWidth:1,
    borderBottomColor:'#ddd'
  },
  member_account:{
    position:'absolute',
    right:35,
    color:'#666'
  },
  member_info_nickname:{
    position:'absolute',
    right:35,
    color:'#666'
  },
  member_date:{
    position:'absolute',
    right:35,
    width:width,
  },
  member_info_listname:{
    fontSize:14
  },
  member_info_con:{
    width:width*0.6,
  },
  member_modal_body:{
    backgroundColor:'rgba(0, 0, 0, 0.3)',
    height:height,
  },
  member_modal:{
    width:width*0.8,
    marginLeft:width*0.1,
    height:130,
    borderRadius:10,
    padding:20,
    backgroundColor:'#fff',
    marginTop:(height/2)-50
  },
  modal_type:{
    fontSize:15,
    color:'#666'
  },
  modal_nickname:{
    marginTop:15,
    marginLeft:5,
    borderBottomWidth:1,
    borderBottomColor:'#ddd',
    fontSize:16
  },
  modal_btn:{
    marginTop:10,
    flexDirection:'row',
    justifyContent:'space-between'
  },
  lasttimeview:{
    marginTop:15,
    alignItems:'center'
  },
  lasttime:{
    color:'#666'
  },
  //我的消息
  msg_container:{
    marginTop:20
  },
  msg_body:{
    marginBottom:15,
    paddingLeft:10,
    paddingRight:10,
    borderBottomWidth:1,
    borderBottomColor:'#eee',
    paddingBottom:15
  },
  msg_list:{
    flexDirection:'row',
    alignItems:'center'
  },
  msg_img:{
    width:40,
    height:40,
    borderRadius:20,
  },
  msg_list_style:{
    marginLeft:15,
    flexDirection:'row',
    justifyContent:'space-between',
    width:width-80
  },
  msg_source:{
    fontSize:16,
  },
  msg_time:{
    fontSize:12,
    color:'#666',
  },
  msg_dsc:{
    marginTop:5,
    fontSize:13,
    color:'#999',
    paddingRight:30
  },
  msg_num_bg:{
    marginTop:5,
    width:15,
    height:15,
    backgroundColor:'#FF6100',
    borderRadius:10,
    alignItems:'center',
    justifyContent:'center'
  },
  msg_num:{
    fontSize:12,
    color:'#fff',
  },
  //设置界面
  set_body:{
    marginTop:15,
    paddingLeft:10,
    paddingRight:10,
    backgroundColor:'#fff'
  },
  set_container:{
    flex:1,
    backgroundColor:'#eee'
  },
  set_list:{
    paddingTop:16,
    paddingBottom:16,
    flexDirection:'row',
    justifyContent:'space-between',
    borderBottomWidth:1,
    borderBottomColor:'#eee',
  },
  set_list_arrow:{
    width:15,
    height:15,
  },
  set_login_out:{
    position:'absolute',
    bottom:0,
    height:50,
    width:width,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#FF9912',
  },
  set_login_out_text:{
    color:'#fff',
    fontSize:18
  },
  //意见反馈
  sug_title:{
    margin:15,
    borderWidth:1,
    borderColor:'#eee'
  },
  sug_text_input:{
    padding:5
  },
  sug_con:{
    margin:15,
    height:200,
    padding:5,
    borderWidth:1,
    textAlignVertical: 'top',
    borderColor:'#eee'
  },
  sug_btn:{
    width:width*0.8,
    height:40,
    backgroundColor:'#ED9121',
    borderRadius:10,
    alignItems:'center',
    justifyContent:'center',
    marginLeft:width*0.1,
    marginTop:100,
  },
  //我的账户
  account_head:{
    width:width,
    height:height*0.2,
    backgroundColor:'#4169E1'
  },
  account_name:{
    marginTop:height*0.05,
    marginLeft:15,
    fontSize:12,
    color:'#fff',
  },
  account_num:{
    marginTop:height*0.02,
    marginLeft:15,
    fontSize:50,
    color:'#fff',
  },
  account_list:{
    flexDirection:'row',
    alignItems:'center',
  },
  account_icon:{
    width:20,
    height:20,
    marginRight:5
  },
  //我的任务
  task_container:{
    backgroundColor:'#e9e9e9',
    flex:1
  },
  task_body:{
    padding:10,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
  },
  task_sel:{
    borderBottomColor:'#4169E1',
    borderBottomWidth:2,
    paddingBottom:5,
  },
  task_unsel:{
    paddingBottom:5,
    borderBottomColor:'transparent',
    borderBottomWidth:2,
  },
  task_sel_text:{
    color:'#4169E1'
  },
  task_list_body:{
    backgroundColor:'#fff',
    padding:10,
    borderRadius:5,
    marginLeft:10,
    marginRight:10
  },
  task_list_item:{
    flexDirection:'row',
  },
  task_img:{
    width:width*0.3,
    height:width*9/40
  },
  task_item_right:{
    marginLeft:10
  },
  //任务详情
  detail_container:{
    padding:10
  },
  detail_desc:{
    marginTop:10,
    marginBottom:10
  },
  detail_time_c:{
    fontSize:12,
    color:'#666'
  },
  detail_title:{
    fontSize:16,
    fontWeight:'600',
  },
  detail_line:{
    height:5,
    backgroundColor:"#eee"
  },
  detail_time:{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:10,
    marginBottom:10
  },
  detail_marginbottom:{
    marginBottom:5
  },
  detail_money:{
    fontSize:16,
    color:'red'
  },
  detail_content:{
    marginTop:5,
    fontSize:13
  },
  detail_foot:{
    position:'absolute',
    bottom:0,
    height:50,
    width:width,
    backgroundColor:'#FF9912',
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center'
  },
  detail_foot_item:{
    width:width/2,
    height:50,
    justifyContent:'center',
    alignItems:'center'
  },
  detail_foot_left:{
    backgroundColor:'skyblue',
  }
}
export {styles as default};
